# Multiple Linear Regression

### Import Library

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Import Dataset

In [3]:
dataset = pd.read_csv('50_Startups.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [23]:
print(x)
print(y)

[[1.65e+05 1.37e+05 4.72e+05 2.00e+00]
 [1.63e+05 1.51e+05 4.44e+05 0.00e+00]
 [1.53e+05 1.01e+05 4.08e+05 1.00e+00]
 [1.44e+05 1.19e+05 3.83e+05 2.00e+00]
 [1.42e+05 9.14e+04 3.66e+05 1.00e+00]
 [1.32e+05 9.98e+04 3.63e+05 2.00e+00]
 [1.35e+05 1.47e+05 1.28e+05 0.00e+00]
 [1.30e+05 1.46e+05 3.24e+05 1.00e+00]
 [1.21e+05 1.49e+05 3.12e+05 2.00e+00]
 [1.23e+05 1.09e+05 3.05e+05 0.00e+00]
 [1.02e+05 1.11e+05 2.29e+05 1.00e+00]
 [1.01e+05 9.18e+04 2.50e+05 0.00e+00]
 [9.39e+04 1.27e+05 2.50e+05 1.00e+00]
 [9.20e+04 1.35e+05 2.53e+05 0.00e+00]
 [1.20e+05 1.57e+05 2.57e+05 1.00e+00]
 [1.15e+05 1.23e+05 2.62e+05 2.00e+00]
 [7.80e+04 1.22e+05 2.64e+05 0.00e+00]
 [9.47e+04 1.45e+05 2.83e+05 2.00e+00]
 [9.17e+04 1.14e+05 2.95e+05 1.00e+00]
 [8.64e+04 1.54e+05 0.00e+00 2.00e+00]
 [7.63e+04 1.14e+05 2.99e+05 0.00e+00]
 [7.84e+04 1.54e+05 3.00e+05 2.00e+00]
 [7.40e+04 1.23e+05 3.03e+05 1.00e+00]
 [6.75e+04 1.06e+05 3.05e+05 1.00e+00]
 [7.70e+04 9.93e+04 1.41e+05 2.00e+00]
 [6.47e+04 1.40e+05 1.38e

### Encoding Categorial Data

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

impute = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],
                           remainder='passthrough')
x = impute.fit_transform(x)

In [24]:
print(x)

[[1.65e+05 1.37e+05 4.72e+05 2.00e+00]
 [1.63e+05 1.51e+05 4.44e+05 0.00e+00]
 [1.53e+05 1.01e+05 4.08e+05 1.00e+00]
 [1.44e+05 1.19e+05 3.83e+05 2.00e+00]
 [1.42e+05 9.14e+04 3.66e+05 1.00e+00]
 [1.32e+05 9.98e+04 3.63e+05 2.00e+00]
 [1.35e+05 1.47e+05 1.28e+05 0.00e+00]
 [1.30e+05 1.46e+05 3.24e+05 1.00e+00]
 [1.21e+05 1.49e+05 3.12e+05 2.00e+00]
 [1.23e+05 1.09e+05 3.05e+05 0.00e+00]
 [1.02e+05 1.11e+05 2.29e+05 1.00e+00]
 [1.01e+05 9.18e+04 2.50e+05 0.00e+00]
 [9.39e+04 1.27e+05 2.50e+05 1.00e+00]
 [9.20e+04 1.35e+05 2.53e+05 0.00e+00]
 [1.20e+05 1.57e+05 2.57e+05 1.00e+00]
 [1.15e+05 1.23e+05 2.62e+05 2.00e+00]
 [7.80e+04 1.22e+05 2.64e+05 0.00e+00]
 [9.47e+04 1.45e+05 2.83e+05 2.00e+00]
 [9.17e+04 1.14e+05 2.95e+05 1.00e+00]
 [8.64e+04 1.54e+05 0.00e+00 2.00e+00]
 [7.63e+04 1.14e+05 2.99e+05 0.00e+00]
 [7.84e+04 1.54e+05 3.00e+05 2.00e+00]
 [7.40e+04 1.23e+05 3.03e+05 1.00e+00]
 [6.75e+04 1.06e+05 3.05e+05 1.00e+00]
 [7.70e+04 9.93e+04 1.41e+05 2.00e+00]
 [6.47e+04 1.40e+05 1.38e

### Splitting Dataset and into Training

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
   x,y, test_size=0.2, random_state=0
)

### Training the Multiple Linear Regression model on the Training Set

In [17]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

### Predecting The Result

In [22]:
y_pred = regressor.predict(x_test)

# np.set_printoptions(precision=2): Mengatur presisi pencetakan numpy menjadi 2
# tempat desimal untuk memperjelas tampilan hasil.
np.set_printoptions(precision=2)

# np.concatenate((...), 1): Menggabungkan kedua array kolom ini secara horizontal
# sehingga setiap baris berisi nilai prediksi (y_pred) dan nilai aktual (y_test)
# yang berpasangan.
print(np.concatenate((y_pred.reshape(len(y_pred), 1),
# y_pred.reshape(len(y_pred), 1): Mengubah array y_pred menjadi array kolom
# (dengan satu kolom dan banyak baris sesuai panjang y_pred).
                      y_test.reshape(len(y_pred),1)),1))
# y_test.reshape(len(y_pred), 1): Mengubah array y_test menjadi array kolom
# (dengan satu kolom dan banyak baris sesuai panjang y_pred).

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


### Label Encoder

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])
x = dataset.iloc[:, :-1].values

In [11]:
print(x)

[[1.6534920e+05 1.3689780e+05 4.7178410e+05 2.0000000e+00]
 [1.6259770e+05 1.5137759e+05 4.4389853e+05 0.0000000e+00]
 [1.5344151e+05 1.0114555e+05 4.0793454e+05 1.0000000e+00]
 [1.4437241e+05 1.1867185e+05 3.8319962e+05 2.0000000e+00]
 [1.4210734e+05 9.1391770e+04 3.6616842e+05 1.0000000e+00]
 [1.3187690e+05 9.9814710e+04 3.6286136e+05 2.0000000e+00]
 [1.3461546e+05 1.4719887e+05 1.2771682e+05 0.0000000e+00]
 [1.3029813e+05 1.4553006e+05 3.2387668e+05 1.0000000e+00]
 [1.2054252e+05 1.4871895e+05 3.1161329e+05 2.0000000e+00]
 [1.2333488e+05 1.0867917e+05 3.0498162e+05 0.0000000e+00]
 [1.0191308e+05 1.1059411e+05 2.2916095e+05 1.0000000e+00]
 [1.0067196e+05 9.1790610e+04 2.4974455e+05 0.0000000e+00]
 [9.3863750e+04 1.2732038e+05 2.4983944e+05 1.0000000e+00]
 [9.1992390e+04 1.3549507e+05 2.5266493e+05 0.0000000e+00]
 [1.1994324e+05 1.5654742e+05 2.5651292e+05 1.0000000e+00]
 [1.1452361e+05 1.2261684e+05 2.6177623e+05 2.0000000e+00]
 [7.8013110e+04 1.2159755e+05 2.6434606e+05 0.0000000e+0