### Belajar Proceesing data with Python

### Import Library Yang Dibutuhkan

In [46]:
# import numpy digunakan untuk komputasi numerik
import numpy as np
# import pandas digunakan untuk manipulasi dan analisis data
import pandas as pd
# import maplotlib.pyplot digunakan untuk membuat visualisasi statis,interaktif dan animasi.
import matplotlib.pyplot as plt
# import os digunakan untuk memeriksa
import os

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [47]:
# os.listDir digunakan untuk memeriksa semua file maupun foler.
print(os.listdir())

['.config', 'Data.csv', 'sample_data']


In [49]:
# dataset = nama variabel
# pd => library dari pyhton untuk manipulasi data
# read_csv digunakan untuk membaca data.csv yaitu data yang sudah saya masukkan ke folder "Data.csv"
# pd.csv('Data.csv')
dataset = pd.read_csv('Data.csv')

header = pd.read_csv('sample_data/california_housing_train.csv')

a = header.iloc[:, :-1]
b = header.iloc[-1, :]
print(a)
print("")
print(b)

print("")

print("=================================")
x = dataset.head()
print(x)
print("=================================")


# iloc digunakan untuk mengakses baris dan kolom berdasarkan posisi indeks
# cara baca [:, :] <= ( baris x kolom ) = [baris, kolom]
x = dataset.iloc[:, :-1].values # disini .iloc[:, :-1] (: membaca semua baris)
# (:-1 memilih semua kolom kecuali kolom terakhir (-1))


# sedangkan ini, memilih semau baris dan hanya kolom terakhir saja.
y = dataset.iloc[:, -1].values # dikarenakan -1 (hanya kolom terakhir saja, tidak menggunakan (:))
# .values digunakan untuk mengubah hasilnya menjadi array NumPy.

print("")
print("Data setelah di Categorial:")
print("==============================")
bc = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],
                       remainder='passthrough')
a = np.array(bc.fit_transform(a))
print(a)
print("==============================")


       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0   

In [50]:
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Taking Care Of Missing data

In [51]:
# sklearn.impute dengan mengimport SimpleImputer:
# digunakan untuk menangani data yang hilang (missing values) dalam dataset.
from sklearn.impute import SimpleImputer

# SimpleImputer adalah sebuah kelas dari modul sklearn.impute
# di scikit-learn yang digunakan untuk mengisi nilai-nilai yang
# hilang dalam dataset.
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
# (missing_values = np.nan) digunakan untuk mencari values yang hilang dengan
# komputasi numerik (np.nan), (strategy = 'mean') digunakan untuk menghitung nilai
# rata - rata (mean).

#impute.fit() digunakan untuk menghitung rata rata dari setiap kolom
impute.fit(x[:,1:3]) # (x[:, 1:3]) = memilih semua baris (:),
# memilih kolom 1 hingga kolom ke 3 yaitu (1:3) =  (Age - Salary - Purchased)

# impute.transform() digunakan untuk mengubah Data Frame mengganti nilai (Nan)
# dengan rata rata yang telah dihitung
x[:, 1:3] = impute.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Categorial Data

## Encoding data kategorikal adalah langkah penting dalam preprocessing data sebelum digunakan dalam model machine learning

In [52]:
# (sklearn.compose import ColumnTransformer) digunakan
# untuk menerapkan transformasi yang berbeda pada kolom yang berbeda dalam dataset.
from sklearn.compose import ColumnTransformer


from sklearn.preprocessing import OneHotEncoder
# (sklearn.preprocessing import OneHotEncoder) digunakan untuk mengubah data kategorikal
# menjadi representasi numerik yang bisa digunakan dalam algoritma machine learning

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# disini kita membuat sebuah variabel ct, yang dimana kita menambahkan data
# ColumnTransformer, Setiap transformer adalah sebuah tuple yang terdiri dari tiga elemen
# 'encoder' = sebuah label atau nama yang bisa Anda gunakan untuk mengidentifikasi transformer tersebut.
# OneHotEncoder() = objek transformer itu sendiri yang akan digunakan untuk mentransformasi data.
# [0] = indeks kolom yang akan diubah menjadi one-hot encoding.
# [:] = semua kolom yang akan diubah menjadi one-hot encoding.
# remainder='passthrough': Menentukan apa yang harus dilakukan dengan kolom yang tidak disebutkan
# dalam transformers.Dalam kasus ini, remainder='passthrough' berarti kolom yang tidak disebutkan
# akan tetap ada dalam dataset dan tidak akan diubah.

# Transformasi data
x = np.array(ct.fit_transform(x))
# fit untuk menghitung nilai rata rata
# transform untuk Menerapkan transformasi yang telah dipelajari pada data x
# np.array() digunakan untuk Mengubah hasil dari fit_transform menjadi sebuah array NumPy.
# Ini dilakukan untuk memastikan bahwa hasilnya dalam format yang konsisten dan mudah digunakan
# dalam analisis atau model machine learning selanjutnya.



In [53]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [54]:
# LabelEncoder adalah alat yang digunakan untuk mengubah label
# kategori menjadi angka.
from sklearn.preprocessing import LabelEncoder


# le = LabelEncoder(): Membuat instance dari LabelEncoder.
le = LabelEncoder()

# y = le.fit_transform(y) Menggunakan instance LabelEncoder untuk mengubah
# label y yang berupa kategori (teks) menjadi angka
y = le.fit_transform(y)

In [55]:
print("Sesudah di Categorial:")
print("=====================================================")
print(y)
print("=====================================================")

print("")

print("Sebelum di Categorial:")
print("=====================================================")
y = dataset.iloc[:, -1].values
print(y)
print("=====================================================")

Sesudah di Categorial:
[0 1 0 0 1 1 0 1 0 1]

Sebelum di Categorial:
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Splitting the dataset into the Training set and Tes set

In [56]:
# sklearn.model_selection digunakan untuk membagi dataset
# menjadi data training dan data testing
from sklearn.model_selection import train_test_split
# train_test_split adalah fungsi dari modul sklearn.model_selection
# yang digunakan untuk membagi dataset menjadi data training dan data testing.

# x_train dan y_train adalah data training untuk fitur dan target.
# x_test dan y_test adalah data testing untuk fitur dan target.
x_train, x_test, y_train, y_test = train_test_split(
# test_size=0.2 mengindikasikan bahwa 20% dari dataset akan digunakan untuk testing
# sementara 80% akan digunakan untuk training.
x, y, test_size=0.2, random_state=1)
# random_state=1 digunakan agar pembagian data menjadi konsisten dan
# dapat direproduksi secara berulang.

In [57]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [58]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [59]:
print(y_train)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes']


In [60]:
print(y_test)

['No' 'Yes']


## Feature Scalling

In [71]:
# StandardScaler digunakan untuk melakukan scaling fitur dengan mengubah fitur-fitur
# numerik sehingga memiliki rata-rata nol dan varians satu.
from sklearn.preprocessing import StandardScaler

# sc adalah variabel yang memanggil objek StandardScaler()
sc = StandardScaler()

# sc.fit_transform(x_train[:, 3:]) menghitung rata-rata dan standar deviasi dari
# kolom ke-3 dan seterusnya ([:, 3:]) dalam x_train, lalu mengubah data tersebut
# sesuai dengan skala yang dihitung.
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

# sc.transform(x_test[:, 3:]) mengubah skala data testing (x_test) menggunakan
# rata-rata dan standar deviasi yang sama seperti yang dihitung dari x_train.
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [66]:
print(x_train)

[[0.0 0.0 1.0 -0.1915918438457855 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057819 -0.07013167641635407]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.30453019390224867 -0.307866172742979]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [67]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830127 -0.9069571034860731]
 [1.0 0.0 0.0 -0.44973664397484414 0.20564033932253023]]
